-file("/Users/thiago/.asdf/installs/erlang/25.0.3/lib/parsetools-2.4/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(build_query_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/build_query_lexer.xrl", 65).

oid(Oid) ->
    S = tl(lists:droplast(Oid)),
    L = string:split(S, ".", all),
    lists:map(fun list_to_integer/1, L).

-file("/Users/thiago/.asdf/installs/erlang/25.0.3/lib/parsetools-2.4/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transition state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/build_query_lexer.erl", 312).
yystate() -> 101.

yystate(104, [110|Ics], Line, Tlen, _, _) ->
    yystate(100, Ics, Line, Tlen+1, 8, Tlen);
yystate(104, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 8, Tlen);
yystate(104, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 8, Tlen);
yystate(104, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 8, Tlen);
yystate(104, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(77, Ics, Line, Tlen+1, 8, Tlen);
yystate(104, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 8, Tlen);
yystate(104, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,104};
yystate(103, [32|Ics], Line, Tlen, _, _) ->
    yystate(103, Ics, Line, Tlen+1, 36, Tlen);
yystate(103, [13|Ics], Line, Tlen, _, _) ->
    yystate(103, Ics, Line, Tlen+1, 36, Tlen);
yystate(103, [9|Ics], Line, Tlen, _, _) ->
    yystate(103, Ics, Line, Tlen+1, 36, Tlen);
yystate(103, [10|Ics], Line, Tlen, _, _) ->
    yystate(103, Ics, Line+1, Tlen+1, 36, Tlen);
yystate(103, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,103};
yystate(102, [110|Ics], Line, Tlen, _, _) ->
    yystate(104, Ics, Line, Tlen+1, 33, Tlen);
yystate(102, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(102, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,102};
yystate(101, [119|Ics], Line, Tlen, Action, Alen) ->
    yystate(97, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [118|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [113|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [107|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [106|Ics], Line, Tlen, Action, Alen) ->
    yystate(86, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line+1, Tlen+1, Action, Alen);
yystate(101, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [C|Ics], Line, Tlen, Action, Alen) when C >= 120, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(101, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,101};
yystate(100, [101|Ics], Line, Tlen, _, _) ->
    yystate(96, Ics, Line, Tlen+1, 33, Tlen);
yystate(100, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(100, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,100};
yystate(99, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(98, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 28, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 28, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 28, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 28, Tlen);
yystate(98, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line,98};
yystate(97, [104|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 33, Tlen);
yystate(97, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(97, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(97, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(97, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(97, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(97, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,97};
yystate(96, [114|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 33, Tlen);
yystate(96, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(96, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,96};
yystate(95, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(99, Ics, Line, Tlen+1, Action, Alen);
yystate(95, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,95};
yystate(94, [110|Ics], Line, Tlen, _, _) ->
    yystate(98, Ics, Line, Tlen+1, 33, Tlen);
yystate(94, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(94, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,94};
yystate(93, [101|Ics], Line, Tlen, _, _) ->
    yystate(89, Ics, Line, Tlen+1, 33, Tlen);
yystate(93, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(93, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,93};
yystate(92, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(92, [32|Ics], Line, Tlen, _, _) ->
    yystate(88, Ics, Line, Tlen+1, 33, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(92, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,92};
yystate(91, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(91, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(91, Ics, Line+1, Tlen+1, Action, Alen);
yystate(91, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(91, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(91, [C|Ics], Line, Tlen, Action, Alen) when C >= 35 ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(91, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,91};
yystate(90, [105|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 33, Tlen);
yystate(90, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(90, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,90};
yystate(89, [114|Ics], Line, Tlen, _, _) ->
    yystate(85, Ics, Line, Tlen+1, 33, Tlen);
yystate(89, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(89, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,89};
yystate(88, [106|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(88, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,88};
yystate(87, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line};
yystate(86, [111|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 33, Tlen);
yystate(86, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(86, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,86};
yystate(85, [101|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 33, Tlen);
yystate(85, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(85, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,85};
yystate(84, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(84, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,84};
yystate(83, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(83, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line+1, Tlen+1, Action, Alen);
yystate(83, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(83, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(83, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(83, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,83};
yystate(82, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line};
yystate(81, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 22, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 22, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 22, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 22, Tlen);
yystate(81, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,81};
yystate(80, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(80, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,80};
yystate(79, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line};
yystate(78, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(82, Ics, Line, Tlen+1, Action, Alen);
yystate(78, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,78};
yystate(77, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,77};
yystate(76, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(76, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,76};
yystate(75, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(74, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Tlen+1, Action, Alen);
yystate(74, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,74};
yystate(73, [114|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 33, Tlen);
yystate(73, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(73, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,73};
yystate(72, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line};
yystate(71, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(70, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(70, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,70};
yystate(69, [117|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 33, Tlen);
yystate(69, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,69};
yystate(68, [114|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 33, Tlen);
yystate(68, [97|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 33, Tlen);
yystate(68, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 113 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,68};
yystate(67, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(66, [106|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(66, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,66};
yystate(65, [101|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 33, Tlen);
yystate(65, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,65};
yystate(64, [111|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 33, Tlen);
yystate(64, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,64};
yystate(63, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(62, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(62, [32|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 33, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,62};
yystate(61, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 23, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 23, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 23, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 23, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line,61};
yystate(60, [109|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 33, Tlen);
yystate(60, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,60};
yystate(59, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(58, [116|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 33, Tlen);
yystate(58, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,58};
yystate(57, [117|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 33, Tlen);
yystate(57, [101|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 33, Tlen);
yystate(57, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 116 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,57};
yystate(56, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,56};
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 0, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,55};
yystate(54, [102|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 33, Tlen);
yystate(54, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,54};
yystate(53, [109|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 33, Tlen);
yystate(53, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,53};
yystate(52, [108|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 33, Tlen);
yystate(52, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,52};
yystate(51, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line};
yystate(50, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,50};
yystate(49, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 10, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 10, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 10, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 10, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,49};
yystate(48, [115|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 33, Tlen);
yystate(48, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,48};
yystate(47, [61|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 3, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,47};
yystate(46, [101|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 33, Tlen);
yystate(46, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,46};
yystate(45, [108|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 33, Tlen);
yystate(45, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,45};
yystate(44, [101|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 33, Tlen);
yystate(44, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,44};
yystate(43, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(42, [107|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 33, Tlen);
yystate(42, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 106 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 108, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,42};
yystate(41, [101|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 33, Tlen);
yystate(41, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,41};
yystate(40, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 24, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 24, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 24, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 24, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,40};
yystate(39, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line};
yystate(38, [105|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 33, Tlen);
yystate(38, [101|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 33, Tlen);
yystate(38, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 104 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,38};
yystate(37, [99|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 33, Tlen);
yystate(37, [97|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(37, [98|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(37, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,37};
yystate(36, [111|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 33, Tlen);
yystate(36, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,36};
yystate(35, [61|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 4, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,35};
yystate(34, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 21, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 21, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 21, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 21, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line,34};
yystate(33, [116|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 33, Tlen);
yystate(33, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,33};
yystate(32, [117|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 33, Tlen);
yystate(32, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,32};
yystate(31, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(30, [116|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 33, Tlen);
yystate(30, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,30};
yystate(29, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 26, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,29};
yystate(28, [110|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 33, Tlen);
yystate(28, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,28};
yystate(27, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(26, [111|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 33, Tlen);
yystate(26, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,26};
yystate(25, [105|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 33, Tlen);
yystate(25, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,25};
yystate(24, [116|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 33, Tlen);
yystate(24, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,24};
yystate(23, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 19, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 19, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 19, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 19, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,23};
yystate(22, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 32, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 32, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 32, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 32, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line,22};
yystate(21, [103|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 33, Tlen);
yystate(21, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,21};
yystate(20, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,20};
yystate(19, [100|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 33, Tlen);
yystate(19, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,19};
yystate(18, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 20, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 20, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 20, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 20, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,18};
yystate(17, [104|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 33, Tlen);
yystate(17, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,17};
yystate(16, [101|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 33, Tlen);
yystate(16, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,16};
yystate(15, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 18, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 18, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 18, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 18, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,15};
yystate(14, [114|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 33, Tlen);
yystate(14, [110|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 33, Tlen);
yystate(14, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 113 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,14};
yystate(13, [116|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 33, Tlen);
yystate(13, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,13};
yystate(12, [116|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 33, Tlen);
yystate(12, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,12};
yystate(11, [115|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 33, Tlen);
yystate(11, [110|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 33, Tlen);
yystate(11, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 114 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,11};
yystate(10, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line};
yystate(9, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(9, [32|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 33, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,9};
yystate(8, [119|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 33, Tlen);
yystate(8, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 118 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 120, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,8};
yystate(7, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 25, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 25, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 25, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 25, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line,7};
yystate(6, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(6, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,6};
yystate(5, [106|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(5, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,5};
yystate(4, [101|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 33, Tlen);
yystate(4, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,4};
yystate(3, [110|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 33, Tlen);
yystate(3, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,3};
yystate(2, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(2, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,2};
yystate(1, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(1, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,1};
yystate(0, [101|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 33, Tlen);
yystate(0, [95|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(77, Ics, Line, Tlen+1, 33, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, _, _, TokenLine) ->
    yyaction_1(TokenLine);
yyaction(2, _, _, TokenLine) ->
    yyaction_2(TokenLine);
yyaction(3, _, _, TokenLine) ->
    yyaction_3(TokenLine);
yyaction(4, _, _, TokenLine) ->
    yyaction_4(TokenLine);
yyaction(5, _, _, TokenLine) ->
    yyaction_5(TokenLine);
yyaction(6, _, _, TokenLine) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine) ->
    yyaction_7(TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, _, _, TokenLine) ->
    yyaction_12(TokenLine);
yyaction(13, _, _, TokenLine) ->
    yyaction_13(TokenLine);
yyaction(14, _, _, TokenLine) ->
    yyaction_14(TokenLine);
yyaction(15, _, _, TokenLine) ->
    yyaction_15(TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, TokenLine) ->
    yyaction_17(TokenLine);
yyaction(18, _, _, TokenLine) ->
    yyaction_18(TokenLine);
yyaction(19, _, _, TokenLine) ->
    yyaction_19(TokenLine);
yyaction(20, _, _, TokenLine) ->
    yyaction_20(TokenLine);
yyaction(21, _, _, TokenLine) ->
    yyaction_21(TokenLine);
yyaction(22, _, _, TokenLine) ->
    yyaction_22(TokenLine);
yyaction(23, _, _, TokenLine) ->
    yyaction_23(TokenLine);
yyaction(24, _, _, TokenLine) ->
    yyaction_24(TokenLine);
yyaction(25, _, _, TokenLine) ->
    yyaction_25(TokenLine);
yyaction(26, _, _, TokenLine) ->
    yyaction_26(TokenLine);
yyaction(27, _, _, TokenLine) ->
    yyaction_27(TokenLine);
yyaction(28, _, _, TokenLine) ->
    yyaction_28(TokenLine);
yyaction(29, _, _, TokenLine) ->
    yyaction_29(TokenLine);
yyaction(30, _, _, TokenLine) ->
    yyaction_30(TokenLine);
yyaction(31, _, _, TokenLine) ->
    yyaction_31(TokenLine);
yyaction(32, _, _, TokenLine) ->
    yyaction_32(TokenLine);
yyaction(33, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_33(TokenChars, TokenLine);
yyaction(34, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_34(TokenChars, TokenLine);
yyaction(35, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_35(TokenChars, TokenLine);
yyaction(36, _, _, _) ->
    yyaction_36();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("src/build_query_lexer.xrl", 7).
yyaction_0(TokenChars, TokenLine) ->
     { token, { number, TokenLine, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_1/1}).
-file("src/build_query_lexer.xrl", 10).
yyaction_1(TokenLine) ->
     { token, { operator, TokenLine, '==' } } .

-compile({inline,yyaction_2/1}).
-file("src/build_query_lexer.xrl", 11).
yyaction_2(TokenLine) ->
     { token, { operator, TokenLine, '!=' } } .

-compile({inline,yyaction_3/1}).
-file("src/build_query_lexer.xrl", 12).
yyaction_3(TokenLine) ->
     { token, { operator, TokenLine, '<' } } .

-compile({inline,yyaction_4/1}).
-file("src/build_query_lexer.xrl", 13).
yyaction_4(TokenLine) ->
     { token, { operator, TokenLine, '>' } } .

-compile({inline,yyaction_5/1}).
-file("src/build_query_lexer.xrl", 14).
yyaction_5(TokenLine) ->
     { token, { operator, TokenLine, '>=' } } .

-compile({inline,yyaction_6/1}).
-file("src/build_query_lexer.xrl", 15).
yyaction_6(TokenLine) ->
     { token, { operator, TokenLine, '<=' } } .

-compile({inline,yyaction_7/1}).
-file("src/build_query_lexer.xrl", 16).
yyaction_7(TokenLine) ->
     { token, { operator, TokenLine, ilike } } .

-compile({inline,yyaction_8/1}).
-file("src/build_query_lexer.xrl", 20).
yyaction_8(TokenLine) ->
     { token, { cmp_in, TokenLine } } .

-compile({inline,yyaction_9/1}).
-file("src/build_query_lexer.xrl", 23).
yyaction_9(TokenLine) ->
     { token, { aggregate, TokenLine, count } } .

-compile({inline,yyaction_10/1}).
-file("src/build_query_lexer.xrl", 24).
yyaction_10(TokenLine) ->
     { token, { aggregate, TokenLine, sum } } .

-compile({inline,yyaction_11/1}).
-file("src/build_query_lexer.xrl", 27).
yyaction_11(TokenLine) ->
     { token, { left_paren, TokenLine } } .

-compile({inline,yyaction_12/1}).
-file("src/build_query_lexer.xrl", 28).
yyaction_12(TokenLine) ->
     { token, { right_paren, TokenLine } } .

-compile({inline,yyaction_13/1}).
-file("src/build_query_lexer.xrl", 29).
yyaction_13(TokenLine) ->
     { token, { '[', TokenLine } } .

-compile({inline,yyaction_14/1}).
-file("src/build_query_lexer.xrl", 30).
yyaction_14(TokenLine) ->
     { token, { ']', TokenLine } } .

-compile({inline,yyaction_15/1}).
-file("src/build_query_lexer.xrl", 33).
yyaction_15(TokenLine) ->
     { token, { dot, TokenLine } } .

-compile({inline,yyaction_16/1}).
-file("src/build_query_lexer.xrl", 34).
yyaction_16(TokenLine) ->
     { token, { comma, TokenLine } } .

-compile({inline,yyaction_17/1}).
-file("src/build_query_lexer.xrl", 35).
yyaction_17(TokenLine) ->
     { token, { all, TokenLine } } .

-compile({inline,yyaction_18/1}).
-file("src/build_query_lexer.xrl", 38).
yyaction_18(TokenLine) ->
     { token, { as, TokenLine } } .

-compile({inline,yyaction_19/1}).
-file("src/build_query_lexer.xrl", 39).
yyaction_19(TokenLine) ->
     { token, { boolean_mult, TokenLine } } .

-compile({inline,yyaction_20/1}).
-file("src/build_query_lexer.xrl", 40).
yyaction_20(TokenLine) ->
     { token, { boolean_add, TokenLine } } .

-compile({inline,yyaction_21/1}).
-file("src/build_query_lexer.xrl", 41).
yyaction_21(TokenLine) ->
     { token, { boolean_negate, TokenLine } } .

-compile({inline,yyaction_22/1}).
-file("src/build_query_lexer.xrl", 42).
yyaction_22(TokenLine) ->
     { token, { where, TokenLine } } .

-compile({inline,yyaction_23/1}).
-file("src/build_query_lexer.xrl", 43).
yyaction_23(TokenLine) ->
     { token, { true, TokenLine } } .

-compile({inline,yyaction_24/1}).
-file("src/build_query_lexer.xrl", 44).
yyaction_24(TokenLine) ->
     { token, { false, TokenLine } } .

-compile({inline,yyaction_25/1}).
-file("src/build_query_lexer.xrl", 45).
yyaction_25(TokenLine) ->
     { token, { between, TokenLine } } .

-compile({inline,yyaction_26/1}).
-file("src/build_query_lexer.xrl", 46).
yyaction_26(TokenLine) ->
     { token, { select, TokenLine } } .

-compile({inline,yyaction_27/1}).
-file("src/build_query_lexer.xrl", 47).
yyaction_27(TokenLine) ->
     { token, { from, TokenLine } } .

-compile({inline,yyaction_28/1}).
-file("src/build_query_lexer.xrl", 48).
yyaction_28(TokenLine) ->
     { token, { join, TokenLine } } .

-compile({inline,yyaction_29/1}).
-file("src/build_query_lexer.xrl", 49).
yyaction_29(TokenLine) ->
     { token, { join, TokenLine } } .

-compile({inline,yyaction_30/1}).
-file("src/build_query_lexer.xrl", 50).
yyaction_30(TokenLine) ->
     { token, { left_join, TokenLine } } .

-compile({inline,yyaction_31/1}).
-file("src/build_query_lexer.xrl", 51).
yyaction_31(TokenLine) ->
     { token, { right_join, TokenLine } } .

-compile({inline,yyaction_32/1}).
-file("src/build_query_lexer.xrl", 52).
yyaction_32(TokenLine) ->
     { token, { on, TokenLine } } .

-compile({inline,yyaction_33/2}).
-file("src/build_query_lexer.xrl", 55).
yyaction_33(TokenChars, TokenLine) ->
     { token, { identifier, TokenLine, TokenChars } } .

-compile({inline,yyaction_34/2}).
-file("src/build_query_lexer.xrl", 57).
yyaction_34(TokenChars, TokenLine) ->
     { token, { quoted, TokenLine, TokenChars } } .

-compile({inline,yyaction_35/2}).
-file("src/build_query_lexer.xrl", 58).
yyaction_35(TokenChars, TokenLine) ->
     { token, { quoted, TokenLine, TokenChars } } .

-compile({inline,yyaction_36/0}).
-file("src/build_query_lexer.xrl", 61).
yyaction_36() ->
     skip_token .

-file("/Users/thiago/.asdf/installs/erlang/25.0.3/lib/parsetools-2.4/include/leexinc.hrl", 313).
